<a href="https://colab.research.google.com/github/mercysigilai/WEEK-4-IP/blob/main/Moringa_Data_Science_Prep_W4_Independent_Project_2021_07_Mercy_Sigilai_DataReport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import pandas
import pandas as pd

# import numpy
import numpy as np

# import datetime
from datetime import datetime

In [4]:
# Reading dataset from csv file

Autolib = pd.read_csv('http://bit.ly/autolib_dataset')
Autolib.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [5]:
# preview first 10 rows of the dataset 

Autolib.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

In [6]:
# preview the last 10 rows of the dataset
Autolib.tail(10)

                                           Address  Cars  ...  hour  minute
4990                    47 boulevard de l'HÃ´pital     0  ...    21      13
4991  56 avenue du MarÃ©chal de Lattre de Tassigny     5  ...    20      43
4992                               3 avenue d'Ivry     0  ...    23       1
4993                    6 avenue Charles-de-Gaulle     6  ...     4      43
4994                              15 rue de Rocroy     0  ...    20      49
4995                           8 avenue MÃ©nelotte     2  ...    11      26
4996                             37 rue de Dantzig     4  ...    16      56
4997                                142 rue du Bac     1  ...     7       1
4998                   2 avenue du Val de Fontenay     2  ...    17      27
4999                           5 Rue Henry Brisson     4  ...    10       2

[10 rows x 25 columns]

In [7]:
# Shape of the dataset 
Autolib.shape

(5000, 25)

In [8]:
# To extract information of the dataset

Autolib.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

In [9]:
# Checking for missing values

Autolib.isnull().sum()

# Displayed comment and Scheduled at has null values and since they are not needed in the analysis, we drop them
Autolib.drop(columns=['Scheduled at', 'Displayed comment'], inplace=True)
Autolib

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 23 columns]

In [10]:
# Checking for duplicates
Autolib.duplicated().sum() 

# There are no duplicates

0

In [11]:
# Select paris from city column

Autolib_paris = Autolib[Autolib['City'] =='Paris'] 

Autolib.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 23 columns]

In [17]:
# Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

Autolib_paris.groupby('Bluecar counter')['hour'].count().sort_values(ascending= True).head(1)

Bluecar counter
7    2
Name: hour, dtype: int64

In [18]:
# What is the most popular hour for returning cars?

Autolib_paris.groupby('Bluecar counter')['hour'].count().sort_values(ascending= False).head(1)

Bluecar counter
0    1029
Name: hour, dtype: int64

In [20]:
# What station is the most popular?
# Overall?
Autolib[(Autolib['Kind'] == 'STATION') & (Autolib['Status'] == 'ok')].groupby('Public name')['Public name'].count().sort_values(ascending= False).head(1)

Public name
Paris/Porte de Montrouge/8    13
Name: Public name, dtype: int64

In [22]:
 # What station is the most popular at the most popular picking hour?
Autolib[(Autolib['Kind'] == 'STATION') & (Autolib['Status'] == 'ok') & (Autolib['hour'] == 4)].groupby('Public name')['Public name'].count().sort_values(ascending= False).head(1)

Public name
Paris/Claude Bernard/16    3
Name: Public name, dtype: int64

In [23]:
# What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
# Overall?

Autolib[(Autolib['Kind'] == 'STATION') & (Autolib['Status'] == 'ok')].groupby('Postal code')['Postal code'].count().sort_values(ascending= False).head(1)

Postal code
75015    220
Name: Postal code, dtype: int64

In [24]:
# What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code at the most popular picking hour?

Autolib[(Autolib['Kind'] == 'STATION') & (Autolib['Status'] == 'ok') & (Autolib['hour'] == 4)].groupby('Postal code')['Postal code'].count().sort_values(ascending= False).head(1)

Postal code
75016    11
Name: Postal code, dtype: int64